
# Setup
title:               rFSMTools
tagline:             A set of tools to execute, debug and build rFSM LUA-based state machines 
url:                 "https://robotology.github.io" # insert your site's URL
baseurl:             "/rfsmTools"

# About/contact

author: # you can edit these to be your personal details
  name:              Nicolo' Genesio
  url:               
  email:             nicolo.genesio@iit.it

author2: # you can edit these to be your personal details
  name:              Ali Paikan
  url:               
  email:             ali.paikan@iit.it

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

# Social
github_username: Nicogene
linkedin_username: nicogene
github_username2: apaikan
linkedin_username2: alipaikan


# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/robotology/rfsmTools

# Gems - Dependencies for this theme
plugins:
  # None currently

# Build settings
markdown:     kramdown
permalink:    pretty
